// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:chatblue/core/hive/hive_adapters.dart';
import 'package:hive_ce/hive.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ChatSessionModelAdapter());
    registerAdapter(MessageModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ChatSessionModelAdapter());
    registerAdapter(MessageModelAdapter());
  }
}
